name: Run WEB Test
run-name: On Push - WEB Test Run
on: [push]

jobs:
  WEB-Test:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
        matrix:
            browser: [chromium, firefox, webkit]    #matriz 
        fail-fast: false    #caso um dos browser falhar ele nao para o teste

    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        
        - name: Install Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install Node.js 19.1
          uses: actions/setup-node@v3
          with:
            node-version:   '19.1' 
        
        - name: Istall Requirements
          run: |
            python -m pip install --upgrade pip
            pip install -U -r requirements.txt
            sudo npm install @playwright/test
            sudo npx playwright install-deps
            rfbrowser init

        - name: Run RF WEB Test
          run: |
            robot -d ./results -v HEADLESS:true \
            -v BROWSER:${{matrix.browser}} tests

        - name: Upload Test Results
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: results-${{matrix.browser}}
            path: ./results
            if-no-files-found: ignore
            retention-days: 2
        
        - name: Download Test Results
          if: always()
          uses: actions/download-artifact@v1
          with:
            name: results-${{matrix.browser}}

        - name: Send Reports
          if: always()
          uses: joonvena/robotframework-reporter-action@v2.1
          with:
            report_path: results-${{matrix.browser}}
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}




